server:
  port: 8989
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz?characterEncoding=UTF-8
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 20MB
  data:
    elasticsearch:
      cluster-nodes: 192.168.94.136:9300
  redis:
    host: 49.233.185.109
    port: 7000
    database: 0

mybatis:
  type-aliases-package: com.lyj.entity
  mapper-locations: classpath:com/lyj/mapper/*Mapper.xml
logging:
  level:
    com.lyj.dao: debug
